
class Thing:
    pass


class Prop:
    pass


def get_link(i): return Thing()


def sensor(target, property): return 0


def control_enabled(target, value): pass
def control_shoot(target, x, y, shoot): pass
def control_color(target, r, g, b): pass


def read(target, position): return 0
def write(target, position, value): pass


def draw_clear(r, g, b): pass
def draw_color(r, g, b, a): pass
def draw_stroke(v): pass
def draw_rect(x, y, w, h): pass
def draw_line_rect(x, y, w, h): pass
def draw_poly(x, y, sides, radius, rotation): pass
def draw_line_poly(x, y, sides, radius, rotation): pass
def draw_triangle(x1, y1, x2, y2, x3, y3): pass
def draw_image(x, y, image, size, rotation): pass


def print(message): pass
def print_flush(target): pass


P_TOTALITEMS = Prop()
P_FIRSTITEM = Prop()
P_TOTALLIQUIDS = Prop()
P_TOTALPOWER = Prop()
P_ITEMCAPACITY = Prop()
P_LIQUIDCAPACITY = Prop()
P_POWERCAPACITY = Prop()
P_POWERNETSTORED = Prop()
P_POWERNETCAPACITY = Prop()
P_POWERNETIN = Prop()
P_POWERNETOUT = Prop()
P_AMMO = Prop()
P_AMMOCAPACITY = Prop()
P_HEALTH = Prop()
P_MAXHEALTH = Prop()
P_HEAT = Prop()
P_EFFICIENCY = Prop()
P_PROGRESS = Prop()
P_TIMESCALE = Prop()
P_ROTATION = Prop()
P_X = Prop()
P_Y = Prop()
P_SHOOTX = Prop()
P_SHOOTY = Prop()
P_SIZE = Prop()
P_DEAD = Prop()
P_RANGE = Prop()
P_SHOOTING = Prop()
P_BOOSTING = Prop()
P_MINEX = Prop()
P_MINEY = Prop()
P_MINING = Prop()
P_TEAM = Prop()
P_TYPE = Prop()
P_FLAG = Prop()
P_CONTROLLED = Prop()
P_CONTROLLER = Prop()
P_COMMANDED = Prop()
P_NAME = Prop()
P_PAYLOADCOUNT = Prop()
P_PAYLOADTYPE = Prop()
P_ENABLED = Prop()

I_COPPER = Thing()
I_LEAD = Thing()
I_COAL = Thing()
I_GRAPHITE = Thing()
I_TITANIUM = Thing()
I_THORIUM = Thing()
I_SILICON = Thing()
I_PLASTANIUM = Thing()
I_PHASE_FABRIC = Thing()
I_SURGE_ALLOY = Thing()
I_SPORE_POD = Thing()
I_SAND = Thing()
I_BLAST_COMPOUND = Thing()
I_PYRATITE = Thing()
I_METAGLASS = Thing()
I_SCRAP = Thing()
L_WATER = Thing()
L_SLAG = Thing()
L_OIL = Thing()
L_CRYOFLUID = Thing()
U_DAGGER = Thing()
U_MACE = Thing()
U_FORTRESS = Thing()
U_NOVA = Thing()
U_PULSAR = Thing()
U_QUASAR = Thing()
U_CRAWLER = Thing()
U_ATRAX = Thing()
U_SPIROCT = Thing()
U_ARKYID = Thing()
U_TOXOPID = Thing()
U_FLARE = Thing()
U_HORIZON = Thing()
U_ZENITH = Thing()
U_ANTUMBRA = Thing()
U_ECLIPSE = Thing()
U_MONO = Thing()
U_POLY = Thing()
U_MEGA = Thing()
U_QUAD = Thing()
U_OCT = Thing()
U_RISSO = Thing()
U_MINKE = Thing()
U_BRYDE = Thing()
U_SEI = Thing()
U_OMURA = Thing()
U_RETUSA = Thing()
U_OXYNOE = Thing()
U_CYERCE = Thing()
U_AEGIRES = Thing()
U_NAVANAX = Thing()
U_ALPHA = Thing()
U_BETA = Thing()
U_GAMMA = Thing()
U_SCEPTER = Thing()
U_REIGN = Thing()
U_VELA = Thing()
U_CORVUS = Thing()
B_PARALLAX = Thing()
B_CLIFF = Thing()
B_SAND_BOULDER = Thing()
B_BASALT_BOULDER = Thing()
B_GRASS = Thing()
B_SLAG = Thing()
B_SPACE = Thing()
B_SALT = Thing()
B_SALT_WALL = Thing()
B_PEBBLES = Thing()
B_TENDRILS = Thing()
B_SAND_WALL = Thing()
B_SPORE_PINE = Thing()
B_SPORE_WALL = Thing()
B_BOULDER = Thing()
B_SNOW_BOULDER = Thing()
B_SNOW_PINE = Thing()
B_SHALE = Thing()
B_SHALE_BOULDER = Thing()
B_MOSS = Thing()
B_SHRUBS = Thing()
B_SPORE_MOSS = Thing()
B_SHALE_WALL = Thing()
B_SCRAP_WALL = Thing()
B_SCRAP_WALL_LARGE = Thing()
B_SCRAP_WALL_HUGE = Thing()
B_SCRAP_WALL_GIGANTIC = Thing()
B_THRUSTER = Thing()
B_KILN = Thing()
B_GRAPHITE_PRESS = Thing()
B_MULTI_PRESS = Thing()
B_CONSTRUCTING = Thing()
B_SPAWN = Thing()
B_CORE_SHARD = Thing()
B_CORE_FOUNDATION = Thing()
B_CORE_NUCLEUS = Thing()
B_DEEPWATER = Thing()
B_WATER = Thing()
B_TAINTED_WATER = Thing()
B_DARKSAND_TAINTED_WATERA = Thing()
B_TAR = Thing()
B_STONE = Thing()
B_SAND = Thing()
B_DARKSAND = Thing()
B_ICE = Thing()
B_SNOW = Thing()
B_CRATERS = Thing()
B_SAND_WATER = Thing()
B_DARKSAND_WATER = Thing()
B_CHAR = Thing()
B_DACITE = Thing()
B_RHYOLITE = Thing()
B_DACITE_WALL = Thing()
B_DACITE_BOULDER = Thing()
B_ICE_SNOW = Thing()
B_STONE_WALL = Thing()
B_ICE_WALL = Thing()
B_SNOW_WALL = Thing()
B_DUNE_WALL = Thing()
B_PINE = Thing()
B_DIRT = Thing()
B_DIRT_WALL = Thing()
B_MUD = Thing()
B_WHITE_TREE_DEAD = Thing()
B_WHITE_TREE = Thing()
B_SPORE_CLUSTER = Thing()
B_METAL_FLOOR = Thing()
B_METAL_FLOOR_2 = Thing()
B_METAL_FLOOR_3 = Thing()
B_METAL_FLOOR_4 = Thing()
B_METAL_FLOOR_5 = Thing()
B_METAL_FLOOR_DAMAGED = Thing()
B_DARK_PANEL_1 = Thing()
B_DARK_PANEL_2 = Thing()
B_DARK_PANEL_3 = Thing()
B_DARK_PANEL_4 = Thing()
B_DARK_PANEL_5 = Thing()
B_DARK_PANEL_6 = Thing()
B_DARK_METAL = Thing()
B_BASALT = Thing()
B_HOTROCK = Thing()
B_MAGMAROCK = Thing()
B_COPPER_WALL = Thing()
B_COPPER_WALL_LARGE = Thing()
B_TITANIUM_WALL = Thing()
B_TITANIUM_WALL_LARGE = Thing()
B_PLASTANIUM_WALL = Thing()
B_PLASTANIUM_WALL_LARGE = Thing()
B_PHASE_WALL = Thing()
B_PHASE_WALL_LARGE = Thing()
B_THORIUM_WALL = Thing()
B_THORIUM_WALL_LARGE = Thing()
B_DOOR = Thing()
B_DOOR_LARGE = Thing()
B_DUO = Thing()
B_SCORCH = Thing()
B_SCATTER = Thing()
B_HAIL = Thing()
B_LANCER = Thing()
B_CONVEYOR = Thing()
B_TITANIUM_CONVEYOR = Thing()
B_PLASTANIUM_CONVEYOR = Thing()
B_ARMORED_CONVEYOR = Thing()
B_JUNCTION = Thing()
B_ROUTER = Thing()
B_DISTRIBUTOR = Thing()
B_SORTER = Thing()
B_INVERTED_SORTER = Thing()
B_MESSAGE = Thing()
B_ILLUMINATOR = Thing()
B_OVERFLOW_GATE = Thing()
B_UNDERFLOW_GATE = Thing()
B_SILICON_SMELTER = Thing()
B_PHASE_WEAVER = Thing()
B_PULVERIZER = Thing()
B_CRYOFLUID_MIXER = Thing()
B_MELTER = Thing()
B_INCINERATOR = Thing()
B_SPORE_PRESS = Thing()
B_SEPARATOR = Thing()
B_COAL_CENTRIFUGE = Thing()
B_POWER_NODE = Thing()
B_POWER_NODE_LARGE = Thing()
B_SURGE_TOWER = Thing()
B_DIODE = Thing()
B_BATTERY = Thing()
B_BATTERY_LARGE = Thing()
B_COMBUSTION_GENERATOR = Thing()
B_STEAM_GENERATOR = Thing()
B_DIFFERENTIAL_GENERATOR = Thing()
B_IMPACT_REACTOR = Thing()
B_MECHANICAL_DRILL = Thing()
B_PNEUMATIC_DRILL = Thing()
B_LASER_DRILL = Thing()
B_WATER_EXTRACTOR = Thing()
B_CULTIVATOR = Thing()
B_CONDUIT = Thing()
B_MECHANICAL_PUMP = Thing()
B_ITEM_SOURCE = Thing()
B_ITEM_VOID = Thing()
B_LIQUID_SOURCE = Thing()
B_LIQUID_VOID = Thing()
B_POWER_VOID = Thing()
B_POWER_SOURCE = Thing()
B_UNLOADER = Thing()
B_VAULT = Thing()
B_WAVE = Thing()
B_TSUNAMI = Thing()
B_SWARMER = Thing()
B_SALVO = Thing()
B_RIPPLE = Thing()
B_PHASE_CONVEYOR = Thing()
B_BRIDGE_CONVEYOR = Thing()
B_PLASTANIUM_COMPRESSOR = Thing()
B_PYRATITE_MIXER = Thing()
B_BLAST_MIXER = Thing()
B_SOLAR_PANEL = Thing()
B_SOLAR_PANEL_LARGE = Thing()
B_OIL_EXTRACTOR = Thing()
B_REPAIR_POINT = Thing()
B_REPAIR_TURRET = Thing()
B_PULSE_CONDUIT = Thing()
B_PLATED_CONDUIT = Thing()
B_PHASE_CONDUIT = Thing()
B_LIQUID_ROUTER = Thing()
B_LIQUID_TANK = Thing()
B_LIQUID_JUNCTION = Thing()
B_BRIDGE_CONDUIT = Thing()
B_ROTARY_PUMP = Thing()
B_THORIUM_REACTOR = Thing()
B_MASS_DRIVER = Thing()
B_BLAST_DRILL = Thing()
B_THERMAL_PUMP = Thing()
B_THERMAL_GENERATOR = Thing()
B_ALLOY_SMELTER = Thing()
B_MENDER = Thing()
B_MEND_PROJECTOR = Thing()
B_SURGE_WALL = Thing()
B_SURGE_WALL_LARGE = Thing()
B_CYCLONE = Thing()
B_FUSE = Thing()
B_SHOCK_MINE = Thing()
B_OVERDRIVE_PROJECTOR = Thing()
B_FORCE_PROJECTOR = Thing()
B_ARC = Thing()
B_RTG_GENERATOR = Thing()
B_SPECTRE = Thing()
B_MELTDOWN = Thing()
B_FORESHADOW = Thing()
B_CONTAINER = Thing()
B_LAUNCH_PAD = Thing()
B_SEGMENT = Thing()
B_COMMAND_CENTER = Thing()
B_GROUND_FACTORY = Thing()
B_AIR_FACTORY = Thing()
B_NAVAL_FACTORY = Thing()
B_ADDITIVE_RECONSTRUCTOR = Thing()
B_MULTIPLICATIVE_RECONSTRUCTOR = Thing()
B_EXPONENTIAL_RECONSTRUCTOR = Thing()
B_TETRATIVE_RECONSTRUCTOR = Thing()
B_PAYLOAD_CONVEYOR = Thing()
B_PAYLOAD_ROUTER = Thing()
B_DUCT = Thing()
B_DUCT_ROUTER = Thing()
B_DUCT_BRIDGE = Thing()
B_PAYLOAD_PROPULSION_TOWER = Thing()
B_PAYLOAD_VOID = Thing()
B_PAYLOAD_SOURCE = Thing()
B_DISASSEMBLER = Thing()
B_SILICON_CRUCIBLE = Thing()
B_OVERDRIVE_DOME = Thing()
B_INTERPLANETARY_ACCELERATOR = Thing()
B_BLOCK_FORGE = Thing()
B_BLOCK_LOADER = Thing()
B_BLOCK_UNLOADER = Thing()
B_SWITCH = Thing()
B_MICRO_PROCESSOR = Thing()
B_LOGIC_PROCESSOR = Thing()
B_HYPER_PROCESSOR = Thing()
B_LOGIC_DISPLAY = Thing()
B_LARGE_LOGIC_DISPLAY = Thing()
B_MEMORY_CELL = Thing()
B_MEMORY_BANK = Thing()
T_BLUE = Thing()
T_CRUX = Thing()
T_SHARDED = Thing()
T_DERELICT = Thing()
T_GREEN = Thing()
T_PURPLE = Thing()
